Ensure expiry is reset on each loop of the ban test
crossedfall/crossed-cogs pull request #25
Opened 2023-11-23 04:18 UTC by optimumtact

Otherwise bans that are active and do not have an expiry (like a perma) will inherit the expiry of the ban before them.

2023-11-24 02:34 UTC, Crossedfall commented
Oh, interesting. I'm not sure that I've noticed this. Can you get me a sample case to reproduce?

2023-11-24 08:59 UTC, optimumtact commented
https://centcom.melonmesa.com/viewer/view/admiralgigatron

Showing as expired in discord, including the same expiry time as the prior ban
![Screenshot from 2023-11-24 21-58-37](https://github.com/Crossedfall/crossed-cogs/assets/2544323/a759d914-2191-4058-ba38-5e22dfd4982b)

active on centcom
![Screenshot from 2023-11-24 21-58-43](https://github.com/Crossedfall/crossed-cogs/assets/2544323/e732ed5c-204d-4407-9ca3-ca2b14decb0c)

2023-11-28 08:21 UTC, Crossedfall requested changes
Minor typo in the fix, we should also correct the status state. Once those are fixed up, I saw that it all worked as expected. Thanks for pushing up a fix

2023-11-28 08:21 UTC, Crossedfall commented on cclookup/cclookup.py
> +                    expiresstr = "Permanent"
```suggestion
                    expires = False
                    expiresstr = "Permanent"
```

2023-11-28 08:21 UTC, Crossedfall commented on cclookup/cclookup.py
> +                            expires = "Permanent"
```suggestion
                            expiresstr = "Permanent"
                            status = "Active"
```

2023-11-30 07:25 UTC, Crossedfall approved these changes

2023-11-30 07:25 UTC, merged